#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser/installer; this wizard tells you exactly what to do\n' "$DIM"
  printf '  and verifies each step. Stop any time with Ctrl-C and re-run later.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE=".sd-setup.env"

# LANG_CHOICE: "ru" or "en". t RU EN prints the right one for say/step/etc.
LANG_CHOICE="${LANG_CHOICE:-}"
if [[ -z "$LANG_CHOICE" ]]; then
  LANG_CHOICE=$(_existing LANG_CHOICE || true)
fi
if [[ -z "$LANG_CHOICE" ]]; then
  printf '\n  Choose language / Выберите язык:\n'
  printf '   [1] Русский (default)\n'
  printf '   [2] English\n'
  printf '  > '
  read -r _lang_reply || true
  case "$_lang_reply" in
    2) LANG_CHOICE="en" ;;
    *) LANG_CHOICE="ru" ;;
  esac
fi
write_env LANG_CHOICE "$LANG_CHOICE"

t() {
  if [[ "$LANG_CHOICE" == "en" ]]; then printf '%s' "$2"; else printf '%s' "$1"; fi
}

banner "$(t "Настройка AUTOMATIC1111 (Stable Diffusion) для PixelForge — Windows + RTX 3060" \
            "AUTOMATIC1111 (Stable Diffusion) setup for PixelForge — Windows + RTX 3060")"

# ── Stage 1: Python 3.10 ──────────────────────────────────────────────────
stage "$(t "Python 3.10 (точная версия — не 3.11, не 3.14)" "Python 3.10 (exact version — not 3.11, not 3.14)")"
say "$(t "AUTOMATIC1111 требует torch==2.1.2, а готовые сборки (wheels) для него есть только под Python 3.10." \
         "AUTOMATIC1111 pins torch==2.1.2, which only has installable wheels for Python 3.10.")"
say "$(t "Более новый Python (3.11, 3.12, 3.14...) не сможет установить torch, либо подтянет несовместимую пару torch/torchvision — именно это вызывало ваши прошлые ошибки." \
         "Newer Python (3.11, 3.12, 3.14...) will fail to install torch, or silently pull an incompatible torch/torchvision pair — that's what caused your earlier errors.")"
warn "$(t "Если 'python' или 'py' на этом ПК уже указывает на 3.11+/3.14 — НЕ удаляйте его, от него могут зависеть другие программы." \
          "If 'python' or 'py' on this PC already points at 3.11+/3.14, DO NOT uninstall it — other tools may depend on it.")"
note "$(t "Мы поставим 3.10 рядом и укажем AUTOMATIC1111 использовать именно её." \
          "We'll install 3.10 side-by-side and point AUTOMATIC1111 at it directly.")"

PYTHON_310=""
if command -v py >/dev/null 2>&1 && py -3.10 --version >/dev/null 2>&1; then
  PYTHON_310=$(py -3.10 -c "import sys; print(sys.executable)" 2>/dev/null | tr -d '\r')
fi

if [[ -n "$PYTHON_310" ]]; then
  step "$(t "Найден Python 3.10: $PYTHON_310" "Found Python 3.10 at: $PYTHON_310")"
else
  open_url "https://www.python.org/downloads/release/python-31011/"
  step "$(t "Скачайте 'Windows installer (64-bit)' внизу страницы." "Download 'Windows installer (64-bit)' at the bottom of the page.")"
  step "$(t "Запустите его. Отметьте 'Add python.exe to PATH' — существующую версию Python удалять не нужно." \
            "Run it. Tick 'Add python.exe to PATH' — it's fine to also keep any existing Python version.")"
  pause "$(t "Установили? Нажмите Enter для проверки." "Installed? Press Enter to verify.")"
  if command -v py >/dev/null 2>&1 && py -3.10 --version >/dev/null 2>&1; then
    PYTHON_310=$(py -3.10 -c "import sys; print(sys.executable)" 2>/dev/null | tr -d '\r')
    step "$(t "Проверено: $PYTHON_310" "Verified: $PYTHON_310")"
  else
    warn "$(t "Python 3.10 всё ещё не найден через launcher 'py'. Откройте НОВОЕ окно терминала (чтобы обновился PATH) и запустите мастер заново." \
              "Still can't find Python 3.10 via the 'py' launcher. Open a NEW terminal window (PATH refresh) and re-run this wizard.")"
    ask PYTHON_310 "$(t "Или вставьте полный путь к python.exe из установки 3.10 (можно оставить пустым и исправить позже):" \
                        "Or paste the full path to python.exe from the 3.10 install directly (leave empty to fix later):")"
  fi
fi
write_env PYTHON_310 "$PYTHON_310"

# ── Stage 2: Git ───────────────────────────────────────────────────────────
stage "Git"
if command -v git >/dev/null 2>&1; then
  step "$(t "Найден: $(git --version)" "Found: $(git --version)")"
else
  open_url "https://git-scm.com/download/win"
  step "$(t "Скачайте и запустите 64-битный установщик, настройки по умолчанию подходят." \
            "Download and run the 64-bit installer, defaults are fine.")"
  pause "$(t "Установили? Нажмите Enter для проверки." "Installed? Press Enter to verify.")"
  if command -v git >/dev/null 2>&1; then
    step "$(t "Проверено: $(git --version)" "Verified: $(git --version)")"
  else
    warn "$(t "git всё ещё не найден — откройте новый терминал и запустите мастер заново." \
              "git still not found — open a new terminal and re-run this wizard.")"
  fi
fi

# ── Stage 3: NVIDIA driver ─────────────────────────────────────────────────
stage "$(t "Драйвер NVIDIA (RTX 3060)" "NVIDIA driver (RTX 3060)")"
if command -v nvidia-smi >/dev/null 2>&1; then
  say "$(t "Вывод nvidia-smi:" "nvidia-smi output:")"
  nvidia-smi || true
  confirm "$(t "Версия драйвера выглядит свежей (обновлялась за последние ~6 месяцев)?" \
              "Does the driver version look current (installed in the last ~6 months)?")" \
    && step "$(t "Хорошо, драйвер в порядке." "Good, driver looks OK.")" \
    || { open_url "https://www.nvidia.com/Download/index.aspx"; step "$(t "Выберите RTX 3060, скачайте и установите последний драйвер Game Ready или Studio, затем перезагрузитесь." "Select RTX 3060, download and install the latest Game Ready or Studio driver, then reboot.")"; pause "$(t "Готово?" "Done?")"; }
else
  warn "$(t "nvidia-smi не найден в этой оболочке (обычное дело для Git Bash — она не всегда в PATH)." \
            "nvidia-smi not found in this shell (normal for Git Bash — it's not always on PATH).")"
  open_url "https://www.nvidia.com/Download/index.aspx"
  step "$(t "Выберите RTX 3060, скачайте и установите последний драйвер, если давно не обновляли, затем перезагрузитесь." \
            "Select RTX 3060, download and install the latest driver if you haven't recently, then reboot.")"
  pause "$(t "Драйвер установлен и обновлён? Нажмите Enter для продолжения." "Driver installed and up to date? Press Enter to continue.")"
fi

# ── Stage 4: Clone AUTOMATIC1111 + enable API flag ────────────────────────
stage "$(t "Клонирование AUTOMATIC1111 и включение --api" "Clone AUTOMATIC1111 + enable --api")"
ask SD_INSTALL_DIR "$(t "Куда клонировать stable-diffusion-webui? (например C:/Users/вы/stable-diffusion-webui, или ~/stable-diffusion-webui в Git Bash):" \
                        "Where should stable-diffusion-webui be cloned? (e.g. C:/Users/you/stable-diffusion-webui, or ~/stable-diffusion-webui in Git Bash):")"
SD_INSTALL_DIR="${SD_INSTALL_DIR/#\~/$HOME}"
write_env SD_INSTALL_DIR "$SD_INSTALL_DIR"

if [[ -d "$SD_INSTALL_DIR/.git" ]]; then
  step "$(t "Репозиторий уже существует в $SD_INSTALL_DIR — клонирование пропущено." "Repo already exists at $SD_INSTALL_DIR — skipping clone.")"
else
  step "$(t "Клонирую AUTOMATIC1111/stable-diffusion-webui в $SD_INSTALL_DIR ..." "Cloning AUTOMATIC1111/stable-diffusion-webui into $SD_INSTALL_DIR ...")"
  git clone --quiet https://github.com/AUTOMATIC1111/stable-diffusion-webui.git "$SD_INSTALL_DIR"
  step "$(t "Склонировано." "Cloned.")"
fi

# set_bat_var KEY VALUE FILE — upsert "set KEY=VALUE" in a .bat file:
#  - never passes VALUE through sed's replacement text: a Windows path full of
#    backslashes hits sed's \U/\L/\E case-conversion escapes and silently
#    mangles itself (e.g. "C:\Users\..." losing chunks of the path). Passing
#    the finished line through awk's ENVIRON (not -v, which also does escape
#    processing) is byte-for-byte safe regardless of what VALUE contains.
#  - if the key doesn't exist yet, inserts the new line BEFORE the first
#    "call ..." line instead of appending at the end of the file — appending
#    after "call webui.bat" would mean the variable is never actually set
#    before the program that's supposed to read it runs.
set_bat_var() {
  local key="$1" value="$2" file="$3" tmp
  tmp=$(mktemp)
  BATVAR_LINE="set ${key}=${value}" BATVAR_KEY="$key" awk '
    BEGIN { done = 0; line = ENVIRON["BATVAR_LINE"]; key = ENVIRON["BATVAR_KEY"] }
    $0 ~ ("^set " key "=") {
      print line
      done = 1
      next
    }
    /^call / && !done {
      print line
      done = 1
    }
    { print }
    END { if (!done) print line }
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
}

WEBUI_USER_BAT="$SD_INSTALL_DIR/webui-user.bat"
if [[ -f "$WEBUI_USER_BAT" ]]; then
  set_bat_var "COMMANDLINE_ARGS" "--api --xformers --listen" "$WEBUI_USER_BAT"
  step "$(t "Включены --api --xformers --listen в webui-user.bat." "Enabled --api --xformers --listen in webui-user.bat.")"
  note "$(t "  --api    → без этого PixelForge вообще не сможет обратиться к серверу." "  --api    → PixelForge needs this to talk to the server at all.")"
  note "$(t "  --listen → сервер начинает отвечать другим устройствам в вашей сети, не только этому ПК (нужно, если PixelForge на другом устройстве)." \
            "  --listen → makes it answer requests from OTHER devices on your home network, not just from this Windows PC itself (needed if PixelForge runs elsewhere).")"
  warn "$(t "Осторожно: --listen открывает сервер для всей домашней сети без пароля. Годится для доверенного домашнего Wi-Fi; не делайте так в публичной/офисной сети." \
            "Security note: --listen exposes the server to your whole home network with no login. Fine on a trusted home Wi-Fi; don't do this on a public/office network.")"

  if [[ -n "${PYTHON_310:-}" ]]; then
    set_bat_var "PYTHON" "$PYTHON_310" "$WEBUI_USER_BAT"
    step "$(t "Закреплён PYTHON=$PYTHON_310 в webui-user.bat (чтобы использовалась именно 3.10, даже если в PATH другая версия)." \
              "Pinned PYTHON=$PYTHON_310 in webui-user.bat (so it uses 3.10 even if another Python is on PATH).")"
  fi

else
  warn "$(t "webui-user.bat не найден в $WEBUI_USER_BAT — добавьте туда 'set COMMANDLINE_ARGS=--api --xformers --listen' вручную." \
            "webui-user.bat not found at $WEBUI_USER_BAT — add 'set COMMANDLINE_ARGS=--api --xformers --listen' to it by hand.")"
fi

# Known upstream issue (since Feb 2026): setuptools 82+ dropped pkg_resources,
# which legacy git-installed packages (openai/CLIP, open_clip, etc.) still
# import at build time, so "Couldn't install clip" / "No module named
# pkg_resources" happens on a fresh install.
# https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/17276
#
# Fix has two parts:
#  1. Pin an old setuptools (69.5.1) in the venv.
#  2. Patch launch_utils.py so its pip install calls for these packages pass
#     --no-build-isolation, so they use that pinned setuptools instead of a
#     fresh one pip would otherwise fetch into a throwaway build environment.
#     (A PIP_NO_BUILD_ISOLATION=1 env var does NOT reliably do this — pip
#     does not expose --no-build-isolation as a settable env var, confirmed
#     by users still hitting the isolated-build-env error with it set.)
if [[ -n "${PYTHON_310:-}" ]]; then
  VENV_DIR="$SD_INSTALL_DIR/venv"
  if [[ ! -d "$VENV_DIR" ]]; then
    step "$(t "Создаю venv с Python 3.10..." "Creating venv with Python 3.10...")"
    "$PYTHON_310" -m venv "$VENV_DIR" 2>/dev/null || note "$(t "Не удалось создать venv отсюда — Windows-путь Python может не работать напрямую в Git Bash, AUTOMATIC1111 создаст его сам при первом запуске." "Couldn't create venv from here — a Windows Python path may not run directly under Git Bash; AUTOMATIC1111 will create it on first launch instead.")"
  fi
  VENV_PYTHON="$VENV_DIR/Scripts/python.exe"
  if [[ -f "$VENV_PYTHON" ]]; then
    step "$(t "Закрепляю setuptools==69.5.1 в venv (чинит ошибку 'No module named pkg_resources' при установке CLIP)..." \
              "Pinning setuptools==69.5.1 in the venv (fixes 'No module named pkg_resources' when installing CLIP)...")"
    "$VENV_PYTHON" -m pip install --quiet --upgrade pip 2>/dev/null || true
    "$VENV_PYTHON" -m pip install --quiet "setuptools==69.5.1" wheel 2>/dev/null || true
  else
    note "$(t "venv ещё не создан — этот шаг применится автоматически при следующем запуске мастера, после первого запуска webui-user.bat." \
              "venv doesn't exist yet — this step will apply automatically the next time you run this wizard, after webui-user.bat has run once.")"
  fi
fi

LAUNCH_UTILS="$SD_INSTALL_DIR/modules/launch_utils.py"
if [[ -f "$LAUNCH_UTILS" ]] && grep -qE 'run_pip\(f"install \{[A-Za-z_]+\}", "' "$LAUNCH_UTILS" 2>/dev/null; then
  if ! grep -q -- '--no-build-isolation' "$LAUNCH_UTILS"; then
    sed -E -i 's/run_pip\(f"install \{([A-Za-z_]+)\}", "/run_pip(f"install {\1} --no-build-isolation", "/g' "$LAUNCH_UTILS"
    step "$(t "Пропатчены установки CLIP/open_clip и похожих пакетов в launch_utils.py — добавлен --no-build-isolation." \
              "Patched the CLIP/open_clip and similar package installs in launch_utils.py to add --no-build-isolation.")"
  else
    note "$(t "launch_utils.py уже пропатчен — пропускаю." "launch_utils.py already patched — skipping.")"
  fi
fi

# Known upstream issue (as of early 2026): Stability-AI deleted/hid the
# Stability-AI/stablediffusion repo that AUTOMATIC1111 clones internally,
# so a fresh install fails with "Repository not found" on that URL. Point it
# at the community mirror instead. See:
# https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/17212
stage "$(t "Фикс: Stability-AI/stablediffusion 404 (известная проблема апстрима)" "Fix: Stability-AI/stablediffusion 404 (known upstream issue)")"
say "$(t "AUTOMATIC1111 внутри себя клонирует второй репозиторий с кодом модели. Stability-AI удалили его, поэтому первая установка падает с 'Repository not found'." \
         "AUTOMATIC1111 internally clones a second repo for the model code. Stability-AI took that repo down, so first-time setup fails with 'Repository not found'.")"
say "$(t "Фикс: указать вместо него рабочее зеркало (w-e-w/stablediffusion)." "Fix: point it at the community mirror (w-e-w/stablediffusion) instead.")"

LAUNCH_UTILS="$SD_INSTALL_DIR/modules/launch_utils.py"
if [[ -f "$LAUNCH_UTILS" ]] && grep -q "Stability-AI/stablediffusion.git" "$LAUNCH_UTILS"; then
  sed -i 's#https://github.com/Stability-AI/stablediffusion.git#https://github.com/w-e-w/stablediffusion.git#' "$LAUNCH_UTILS"
  step "$(t "modules/launch_utils.py пропатчен на рабочее зеркало." "Patched modules/launch_utils.py to use the working mirror.")"
else
  note "$(t "launch_utils.py уже пропатчен, либо этому чекауту фикс не нужен (апстрим мог уже починить) — пропускаю." \
            "launch_utils.py already patched, or this checkout doesn't need it (upstream may have fixed it) — skipping.")"
fi

BROKEN_REPO_DIR="$SD_INSTALL_DIR/repositories/stable-diffusion-stability-ai"
if [[ -d "$BROKEN_REPO_DIR" ]]; then
  step "$(t "Удаляю ранее наполовину склонированную repositories/stable-diffusion-stability-ai, чтобы она переклонировалась чисто." \
            "Removing a previously half-cloned repositories/stable-diffusion-stability-ai so it re-clones cleanly.")"
  rm -rf "$BROKEN_REPO_DIR"
fi
note "$(t "Если при запуске снова 404 — значит апстрим опять сменил зеркало, проверьте:" \
          "If this still 404s on launch, it means upstream changed the mirror again — check:")"
note "  https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/17212"

# ── Stage 5: Pixel-art model ───────────────────────────────────────────────
stage "$(t "Pixel-art модель" "Pixel-art model")"
say "$(t "Промпты PixelForge работают с любым чекпоинтом SD 1.5, но модель, дообученная на пиксель-арте, даёт заметно более чистый результат." \
         "PixelForge's prompts work with any SD 1.5 checkpoint, but a model fine-tuned on pixel art gives much cleaner results.")"
open_url "https://civitai.com/search/models?query=pixel%20art"
step "$(t "Выберите чекпоинт с тегом 'pixel art' (например 'All-In-One-Pixel-Model'), скачайте файл .safetensors." \
          "Pick a checkpoint tagged 'pixel art' (e.g. 'All-In-One-Pixel-Model'), download the .safetensors file.")"
note "$(t "Для скачивания на Civitai может понадобиться бесплатный аккаунт." "Civitai downloads may require a free account login.")"
ask MODEL_FILE "$(t "Полный путь к скачанному .safetensors файлу (оставьте пустым, чтобы пропустить и добавить позже):" \
                    "Full path to the downloaded .safetensors file (leave empty to skip and add it later):")"
if [[ -n "$MODEL_FILE" ]]; then
  MODEL_FILE="${MODEL_FILE/#\~/$HOME}"
  MODELS_DIR="$SD_INSTALL_DIR/models/Stable-diffusion"
  mkdir -p "$MODELS_DIR"
  if [[ -f "$MODEL_FILE" ]]; then
    cp -v "$MODEL_FILE" "$MODELS_DIR/"
    step "$(t "Модель скопирована в $MODELS_DIR" "Copied model into $MODELS_DIR")"
  else
    warn "$(t "Файл не найден по пути $MODEL_FILE — скопируйте его в $MODELS_DIR вручную." \
              "File not found at $MODEL_FILE — copy it into $MODELS_DIR manually.")"
  fi
else
  warn "$(t "Пропущено — скопируйте .safetensors модель в $SD_INSTALL_DIR/models/Stable-diffusion вручную перед генерацией." \
            "Skipped — copy a .safetensors model into $SD_INSTALL_DIR/models/Stable-diffusion manually before generating.")"
fi

# ── Stage 6: Launch WebUI, find the LAN IP, verify the API ─────────────────
stage "$(t "Запуск WebUI, поиск сетевого адреса, проверка API" "Launch WebUI, find its network address, verify the API")"
say "$(t "webui-user.bat работает на переднем плане и должен оставаться запущенным, пока используется PixelForge." \
         "webui-user.bat runs in the foreground and must stay running while PixelForge is used.")"
step "$(t "Откройте НОВОЕ окно терминала (cmd, PowerShell или Git Bash) и выполните:" \
          "Open a NEW terminal window (cmd, PowerShell, or Git Bash) and run:")"
note "  cd \"$SD_INSTALL_DIR\" && webui-user.bat"
step "$(t "Дождитесь строки в консоли 'Running on local URL: http://0.0.0.0:7860' (0.0.0.0 означает, что --listen сработал)." \
          "Wait for the console to print 'Running on local URL: http://0.0.0.0:7860' (note 0.0.0.0 — that's --listen working).")"
note "$(t "Первый запуск скачивает дополнительные зависимости — может занять 10-20 минут." "First launch downloads extra dependencies — can take 10-20 minutes.")"
pause "$(t "WebUI запущен? Нажмите Enter, чтобы найти сетевой адрес этого ПК." "WebUI running? Press Enter to find this PC's network address.")"

LAN_IP=""
if command -v ipconfig.exe >/dev/null 2>&1; then
  LAN_IP=$(ipconfig.exe | grep -A5 "Wireless LAN adapter Wi-Fi" | grep -m1 "IPv4" | sed 's/.*: //' | tr -d '\r')
  [[ -z "$LAN_IP" ]] && LAN_IP=$(ipconfig.exe | grep -m1 "IPv4" | sed 's/.*: //' | tr -d '\r')
elif command -v ipconfig >/dev/null 2>&1; then
  LAN_IP=$(ipconfig | grep -m1 "IPv4" | sed 's/.*: //' | tr -d '\r')
fi

if [[ -n "$LAN_IP" ]]; then
  step "$(t "Локальный сетевой адрес этого ПК: $LAN_IP" "This PC's local network address: $LAN_IP")"
  note "$(t "На ДРУГОМ устройстве (Mac) нужно будет ввести: http://$LAN_IP:7860" "On the OTHER device (Mac), you'll enter: http://$LAN_IP:7860")"
  write_env WINDOWS_LAN_IP "$LAN_IP"
else
  warn "$(t "Не удалось определить IP автоматически. Выполните 'ipconfig' сами и найдите 'IPv4-адрес' под вашим Wi-Fi/Ethernet адаптером — выглядит как 192.168.x.x." \
            "Couldn't auto-detect the IP. Run 'ipconfig' yourself and look for 'IPv4 Address' under your Wi-Fi/Ethernet adapter — it looks like 192.168.x.x.")"
  ask WINDOWS_LAN_IP "$(t "Вставьте этот IPv4-адрес:" "Paste that IPv4 address here:")"
  write_env WINDOWS_LAN_IP "$WINDOWS_LAN_IP"
  LAN_IP="$WINDOWS_LAN_IP"
fi

step "$(t "Windows Firewall может блокировать входящие подключения на порт 7860 с других устройств." \
          "Windows Firewall may block incoming connections on port 7860 from other devices.")"
note "$(t "Если проверка ниже не пройдёт: Безопасность Windows → Брандмауэр и защита сети →" \
          "If the check below fails, allow it: Windows Security → Firewall & network protection →")"
note "$(t "  Разрешить приложение через брандмауэр → Разрешить другое приложение → указать python.exe в venv, либо" \
          "  Allow an app through firewall → Allow another app → browse to python.exe in the venv, or")"
note "$(t "  проще всего — создать правило для входящих подключений на TCP порт 7860 в 'Брандмауэр Windows в режиме повышенной безопасности'." \
          "  simplest: create an inbound rule for TCP port 7860 in 'Windows Defender Firewall with Advanced Security'.")"
confirm "$(t "Это ДОМАШНЯЯ сеть (не публичная/офисная)? У --listen нет пароля, включайте это только в доверенной сети." \
             "Is this a HOME network (not a public/office one)? --listen has no login, so only do this on a trusted network.")" \
  || warn "$(t "Подумайте о том, чтобы не открывать --listen в этой сети, либо ограничить доступ правилом файрвола только для IP вашего Mac." \
               "Consider not exposing --listen on this network, or restrict it with a firewall rule to your Mac's IP only.")"

if command -v curl >/dev/null 2>&1; then
  if curl -s -o /dev/null -w '%{http_code}' "http://localhost:7860/sdapi/v1/sd-models" | grep -q '^200$'; then
    step "$(t "API доступен локально на http://localhost:7860 ✓" "API reachable locally at http://localhost:7860 ✓")"
  else
    warn "$(t "Не удалось достучаться до http://localhost:7860/sdapi/v1/sd-models — проверьте консоль WebUI на ошибки и убедитесь что --api указан в COMMANDLINE_ARGS." \
              "Couldn't reach http://localhost:7860/sdapi/v1/sd-models — check the WebUI console for errors and confirm --api is in COMMANDLINE_ARGS.")"
  fi
  if [[ -n "$LAN_IP" ]] && curl -s -o /dev/null -w '%{http_code}' "http://$LAN_IP:7860/sdapi/v1/sd-models" | grep -q '^200$'; then
    step "$(t "API также доступен по сети на http://$LAN_IP:7860 ✓ — именно этот адрес нужно ввести на Mac." \
              "API also reachable over the network at http://$LAN_IP:7860 ✓ — this is what you'll enter on the Mac.")"
  else
    warn "$(t "Пока недоступен по http://$LAN_IP:7860 отсюда — это нормально, если вы проверяете с самого Windows-ПК; настоящая проверка — с Mac (следующий шаг)." \
              "Not reachable at http://$LAN_IP:7860 from here yet — that's OK if you're testing from the Windows PC itself; the real test is from the Mac (next stage).")"
  fi
else
  warn "$(t "curl не найден — откройте http://localhost:7860 в браузере, чтобы убедиться что WebUI запущен." \
            "curl not found — open http://localhost:7860 in a browser to confirm the WebUI is up.")"
fi

# ── Stage 7: End-to-end test through PixelForge ────────────────────────────
stage "$(t "Проверка генерации через PixelForge" "Test generation through PixelForge")"
say "$(t "PixelForge может работать на ЭТОМ Windows-ПК, либо на другом устройстве (например, Mac) в той же сети." \
         "PixelForge might run on THIS Windows PC, or on another device (e.g. a Mac) on the same network.")"
say "$(t "В любом случае в левой панели PixelForge есть поле 'Адрес Stable Diffusion':" \
         "Either way, in PixelForge's left panel there's now an 'Адрес Stable Diffusion' field:")"
step "$(t "На ЭТОМ Windows-ПК:            http://localhost:7860" "On THIS Windows PC:            http://localhost:7860")"
step "$(t "На другом устройстве (Mac...): http://$LAN_IP:7860" "On another device (Mac, etc.): http://$LAN_IP:7860")"
note "$(t "Вставьте нужный адрес и нажмите 'Проверить' — точка должна стать зелёной." "Paste the right one in, then click 'Проверить' — the dot should turn green.")"

ask PIXELFORGE_DIR "$(t "Путь к папке проекта pixel-forge НА ЭТОМ ПК (оставьте пустым, если PixelForge на другом устройстве):" \
                        "Path to the pixel-forge project folder ON THIS PC (leave empty if PixelForge runs on another device):")"
PIXELFORGE_DIR="${PIXELFORGE_DIR/#\~/$HOME}"
write_env PIXELFORGE_DIR "$PIXELFORGE_DIR"

if [[ -n "$PIXELFORGE_DIR" && -d "$PIXELFORGE_DIR" ]]; then
  step "$(t "Найден проект в $PIXELFORGE_DIR" "Found project at $PIXELFORGE_DIR")"
  if [[ ! -d "$PIXELFORGE_DIR/node_modules" ]]; then
    note "$(t "node_modules отсутствует — сначала выполняю npm install." "node_modules missing — running npm install first.")"
    (cd "$PIXELFORGE_DIR" && npm install)
  fi
  say "$(t "Запуск самого приложения — вручную: выполните это сами, чтобы увидеть окно." \
           "Launching the app itself is manual: run this yourself so you can see the window.")"
  step "$(t "В терминале: cd \"$PIXELFORGE_DIR\" && npm start" "In a terminal: cd \"$PIXELFORGE_DIR\" && npm start")"
elif [[ -n "$PIXELFORGE_DIR" ]]; then
  warn "$(t "Путь не найден: $PIXELFORGE_DIR" "Path not found: $PIXELFORGE_DIR")"
else
  say "$(t "Хорошо — перейдите на ДРУГОЕ устройство, откройте PixelForge и укажите в поле адреса http://$LAN_IP:7860" \
           "OK — go to the OTHER device, open PixelForge, and set the address field to http://$LAN_IP:7860")"
fi

step "$(t "В приложении: переключитесь на режим 'Stable Diffusion', вставьте нужный адрес сервера, нажмите 'Проверить' (точка должна стать зелёной)." \
          "In the app: switch mode to 'Stable Diffusion', paste the right server address, click 'Проверить' (dot should go green).")"
step "$(t "Введите описание (например 'дерево дуб осенью, вид сбоку'), выберите 32x32, нажмите СГЕНЕРИРОВАТЬ (или Ctrl+Enter)." \
          "Type a description (e.g. 'дерево дуб осенью, вид сбоку'), pick 32x32, click СГЕНЕРИРОВАТЬ (or Ctrl+Enter).")"
pause "$(t "Нажмите Enter, когда сделаете это и будете готовы подтвердить." "Press Enter once you've done that and are ready to confirm.")"
confirm "$(t "Появился ли спрайт в центральной панели?" "Did a sprite appear in the center panel?")" \
  && step "$(t "🎉 Всё работает: PixelForge → AUTOMATIC1111 → спрайт." "🎉 End-to-end works: PixelForge → AUTOMATIC1111 → sprite.")" \
  || warn "$(t "Если не сработало: проверьте текст ошибки у индикатора подключения в PixelForge, консоль WebUI на входящий запрос, и что Windows Firewall разрешает порт 7860 при проверке с другого устройства." \
               "If it failed: check the connection dot's error text in PixelForge, the WebUI console for the incoming request, and that Windows Firewall allows port 7860 if testing from another device.")"

finish
