#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser/installer; this wizard tells you exactly what to do\n' "$DIM"
  printf '  and verifies each step. Stop any time with Ctrl-C and re-run later.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=".sd-setup.env"

banner "AUTOMATIC1111 (Stable Diffusion) setup for PixelForge — Windows + RTX 3060"

# ── Stage 1: Python 3.10 ──────────────────────────────────────────────────
stage "Python 3.10"
say "AUTOMATIC1111 needs Python 3.10.x specifically (not 3.11+)."
if command -v python >/dev/null 2>&1 && python --version 2>&1 | grep -q "3.10"; then
  step "Found: $(python --version 2>&1)"
else
  open_url "https://www.python.org/downloads/release/python-31011/"
  step "Download 'Windows installer (64-bit)' at the bottom of the page."
  step "Run it. IMPORTANT: tick 'Add python.exe to PATH' on the first screen."
  pause "Installed? Press Enter to verify."
  if python --version 2>&1 | grep -q "3.10"; then
    step "Verified: $(python --version 2>&1)"
  else
    warn "python --version didn't report 3.10.x — open a NEW terminal window (PATH refresh) and re-run this wizard."
  fi
fi

# ── Stage 2: Git ───────────────────────────────────────────────────────────
stage "Git"
if command -v git >/dev/null 2>&1; then
  step "Found: $(git --version)"
else
  open_url "https://git-scm.com/download/win"
  step "Download and run the 64-bit installer, defaults are fine."
  pause "Installed? Press Enter to verify."
  if command -v git >/dev/null 2>&1; then
    step "Verified: $(git --version)"
  else
    warn "git still not found — open a new terminal and re-run this wizard."
  fi
fi

# ── Stage 3: NVIDIA driver ─────────────────────────────────────────────────
stage "NVIDIA driver (RTX 3060)"
if command -v nvidia-smi >/dev/null 2>&1; then
  say "nvidia-smi output:"
  nvidia-smi || true
  confirm "Does the driver version look current (installed in the last ~6 months)?" \
    && step "Good, driver looks OK." \
    || { open_url "https://www.nvidia.com/Download/index.aspx"; step "Select RTX 3060, download and install the latest Game Ready or Studio driver, then reboot."; pause "Done?"; }
else
  warn "nvidia-smi not found in this shell (normal for Git Bash — it's not always on PATH)."
  open_url "https://www.nvidia.com/Download/index.aspx"
  step "Select RTX 3060, download and install the latest driver if you haven't recently, then reboot."
  pause "Driver installed and up to date? Press Enter to continue."
fi

# ── Stage 4: Clone AUTOMATIC1111 + enable API flag ────────────────────────
stage "Clone AUTOMATIC1111 + enable --api"
ask SD_INSTALL_DIR "Where should stable-diffusion-webui be cloned? (e.g. C:/Users/you/stable-diffusion-webui, or ~/stable-diffusion-webui in Git Bash):"
SD_INSTALL_DIR="${SD_INSTALL_DIR/#\~/$HOME}"
write_env SD_INSTALL_DIR "$SD_INSTALL_DIR"

if [[ -d "$SD_INSTALL_DIR/.git" ]]; then
  step "Repo already exists at $SD_INSTALL_DIR — skipping clone."
else
  step "Cloning AUTOMATIC1111/stable-diffusion-webui into $SD_INSTALL_DIR ..."
  git clone --quiet https://github.com/AUTOMATIC1111/stable-diffusion-webui.git "$SD_INSTALL_DIR"
  step "Cloned."
fi

WEBUI_USER_BAT="$SD_INSTALL_DIR/webui-user.bat"
if [[ -f "$WEBUI_USER_BAT" ]]; then
  if grep -q "^set COMMANDLINE_ARGS=" "$WEBUI_USER_BAT"; then
    sed -i 's/^set COMMANDLINE_ARGS=.*/set COMMANDLINE_ARGS=--api --xformers --listen/' "$WEBUI_USER_BAT"
  else
    printf '\nset COMMANDLINE_ARGS=--api --xformers --listen\n' >> "$WEBUI_USER_BAT"
  fi
  step "Enabled --api --xformers --listen in webui-user.bat."
  note "  --api    → PixelForge needs this to talk to the server at all."
  note "  --listen → makes it answer requests from OTHER devices on your home network,"
  note "             not just from this Windows PC itself (needed if PixelForge runs elsewhere)."
  warn "Security note: --listen exposes the server to your whole home network with no login. Fine on a trusted home Wi-Fi; don't do this on a public/office network."
else
  warn "webui-user.bat not found at $WEBUI_USER_BAT — add 'set COMMANDLINE_ARGS=--api --xformers --listen' to it by hand."
fi

# ── Stage 5: Pixel-art model ───────────────────────────────────────────────
stage "Pixel-art model"
say "PixelForge's prompts work with any SD 1.5 checkpoint, but a model fine-tuned"
say "on pixel art gives much cleaner results."
open_url "https://civitai.com/search/models?query=pixel%20art"
step "Pick a checkpoint tagged 'pixel art' (e.g. 'All-In-One-Pixel-Model'), download the .safetensors file."
note "Civitai downloads may require a free account login."
ask MODEL_FILE "Full path to the downloaded .safetensors file (leave empty to skip and add it later):"
if [[ -n "$MODEL_FILE" ]]; then
  MODEL_FILE="${MODEL_FILE/#\~/$HOME}"
  MODELS_DIR="$SD_INSTALL_DIR/models/Stable-diffusion"
  mkdir -p "$MODELS_DIR"
  if [[ -f "$MODEL_FILE" ]]; then
    cp -v "$MODEL_FILE" "$MODELS_DIR/"
    step "Copied model into $MODELS_DIR"
  else
    warn "File not found at $MODEL_FILE — copy it into $MODELS_DIR manually."
  fi
else
  warn "Skipped — copy a .safetensors model into $SD_INSTALL_DIR/models/Stable-diffusion manually before generating."
fi

# ── Stage 6: Launch WebUI, find the LAN IP, verify the API ─────────────────
stage "Launch WebUI, find its network address, verify the API"
say "webui-user.bat runs in the foreground and must stay running while PixelForge is used."
step "Open a NEW terminal window (cmd, PowerShell, or Git Bash) and run:"
note "  cd \"$SD_INSTALL_DIR\" && webui-user.bat"
step "Wait for the console to print 'Running on local URL: http://0.0.0.0:7860' (note 0.0.0.0 — that's --listen working)."
note "First launch downloads extra dependencies — can take 10-20 minutes."
pause "WebUI running? Press Enter to find this PC's network address."

LAN_IP=""
if command -v ipconfig.exe >/dev/null 2>&1; then
  LAN_IP=$(ipconfig.exe | grep -A5 "Wireless LAN adapter Wi-Fi" | grep -m1 "IPv4" | sed 's/.*: //' | tr -d '\r')
  [[ -z "$LAN_IP" ]] && LAN_IP=$(ipconfig.exe | grep -m1 "IPv4" | sed 's/.*: //' | tr -d '\r')
elif command -v ipconfig >/dev/null 2>&1; then
  LAN_IP=$(ipconfig | grep -m1 "IPv4" | sed 's/.*: //' | tr -d '\r')
fi

if [[ -n "$LAN_IP" ]]; then
  step "This PC's local network address: $LAN_IP"
  note "On the OTHER device (Mac), you'll enter: http://$LAN_IP:7860"
  write_env WINDOWS_LAN_IP "$LAN_IP"
else
  warn "Couldn't auto-detect the IP. Run 'ipconfig' yourself and look for 'IPv4 Address' under your Wi-Fi/Ethernet adapter — it looks like 192.168.x.x."
  ask WINDOWS_LAN_IP "Paste that IPv4 address here:"
  write_env WINDOWS_LAN_IP "$WINDOWS_LAN_IP"
  LAN_IP="$WINDOWS_LAN_IP"
fi

step "Windows Firewall may block incoming connections on port 7860 from other devices."
note "If the check below fails, allow it: Windows Security → Firewall & network protection →"
note "  Allow an app through firewall → Allow another app → browse to python.exe in the venv, or"
note "  simplest: create an inbound rule for TCP port 7860 in 'Windows Defender Firewall with Advanced Security'."
confirm "Is this a HOME network (not a public/office one)? --listen has no login, so only do this on a trusted network." \
  || warn "Consider not exposing --listen on this network, or restrict it with a firewall rule to your Mac's IP only."

if command -v curl >/dev/null 2>&1; then
  if curl -s -o /dev/null -w '%{http_code}' "http://localhost:7860/sdapi/v1/sd-models" | grep -q '^200$'; then
    step "API reachable locally at http://localhost:7860 ✓"
  else
    warn "Couldn't reach http://localhost:7860/sdapi/v1/sd-models — check the WebUI console for errors and confirm --api is in COMMANDLINE_ARGS."
  fi
  if [[ -n "$LAN_IP" ]] && curl -s -o /dev/null -w '%{http_code}' "http://$LAN_IP:7860/sdapi/v1/sd-models" | grep -q '^200$'; then
    step "API also reachable over the network at http://$LAN_IP:7860 ✓ — this is what you'll enter on the Mac."
  else
    warn "Not reachable at http://$LAN_IP:7860 from here yet — that's OK if you're testing from the Windows PC itself; the real test is from the Mac (next stage)."
  fi
else
  warn "curl not found — open http://localhost:7860 in a browser to confirm the WebUI is up."
fi

# ── Stage 7: End-to-end test through PixelForge ────────────────────────────
stage "Test generation through PixelForge"
say "PixelForge might run on THIS Windows PC, or on another device (e.g. a Mac) on the same network."
say "Either way, in PixelForge's left panel there's now an 'Адрес Stable Diffusion' field:"
step "On THIS Windows PC:            http://localhost:7860"
step "On another device (Mac, etc.): http://$LAN_IP:7860"
note "Paste the right one in, then click 'Проверить' — the dot should turn green."

ask PIXELFORGE_DIR "Path to the pixel-forge project folder ON THIS PC (leave empty if PixelForge runs on another device):"
PIXELFORGE_DIR="${PIXELFORGE_DIR/#\~/$HOME}"
write_env PIXELFORGE_DIR "$PIXELFORGE_DIR"

if [[ -n "$PIXELFORGE_DIR" && -d "$PIXELFORGE_DIR" ]]; then
  step "Found project at $PIXELFORGE_DIR"
  if [[ ! -d "$PIXELFORGE_DIR/node_modules" ]]; then
    note "node_modules missing — running npm install first."
    (cd "$PIXELFORGE_DIR" && npm install)
  fi
  say "Launching the app itself is manual: run this yourself so you can see the window."
  step "In a terminal: cd \"$PIXELFORGE_DIR\" && npm start"
elif [[ -n "$PIXELFORGE_DIR" ]]; then
  warn "Path not found: $PIXELFORGE_DIR"
else
  say "OK — go to the OTHER device, open PixelForge, and set the address field to http://$LAN_IP:7860"
fi

step "In the app: switch mode to 'Stable Diffusion', paste the right server address, click 'Проверить' (dot should go green)."
step "Type a description (e.g. 'дерево дуб осенью, вид сбоку'), pick 32x32, click СГЕНЕРИРОВАТЬ (or Ctrl+Enter)."
pause "Press Enter once you've done that and are ready to confirm."
confirm "Did a sprite appear in the center panel?" \
  && step "🎉 End-to-end works: PixelForge → AUTOMATIC1111 → sprite." \
  || warn "If it failed: check the connection dot's error text in PixelForge, the WebUI console for the incoming request, and that Windows Firewall allows port 7860 if testing from another device."

finish
